conda env

diff --git a/.github/workflows/demo_train_test.yml b/.github/workflows/demo_train_test.yml
--- a/.github/workflows/demo_train_test.yml
+++ b/.github/workflows/demo_train_test.yml
@@ -106,9 +106,13 @@ jobs:
           cd $PROJECT_ROOT
 
           # Install Megatron-LM-FL
-          pip install megatron_core==0.1.0+megatron0.15.0rc7 \
-            --extra-index-url https://resource.flagos.net/repository/flagos-pypi-hosted/simple \
-            || { echo "❌ Megatron-LM-FL install failed"; exit 1; }
+          git clone \
+            "https://github.com/flagos-ai/Megatron-LM-FL.git" /tmp/Megatron-LM-FL
+          git -C /tmp/Megatron-LM-FL checkout d092f8df49f7c0b5b4cae42d036b7e4a26b8fc81
+
+          echo "Installing Megatron-LM-FL via pip..."
+          pip install /tmp/Megatron-LM-FL --no-build-isolation --root-user-action=ignore \
+            || { echo "Megatron-LM-FL install failed"; exit 1; }
           echo "✅ Megatron-LM-FL installed successfully"
 
           # Install TransformerEngine-FL and dependencies
@@ -130,7 +134,7 @@ jobs:
         run: |
           source /etc/profile.d/conda.sh
           conda activate base
-          
+
           set -euo pipefail
           cd $PROJECT_ROOT
 
